name: Publish Extension

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Package VSIX
        run: npx @vscode/vsce package

      - name: Publish to VS Code Marketplace
        run: npx @vscode/vsce publish --pat "${VSCE_PAT}" --packagePath *.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
